### ISSUE TITLE
About  results on FGVC-Aircraft

### ISSUE THREAD

**Issue by Joseph-EGWang** [CVMI-Lab/SimGCD#8]
The results we achieve on some datasets cannot reach the ones mentioned in the paper (such as Aircraft). Could you please provide  models trained on each dataset so that we can conduct new studies based on your research? Thanks a lot.

**Comment by xwen99** [comment]
Hi, thanks for raising this issue. Since the results of different runs could vary a lot, our provided results are all from multiple models, so uploading the weight of a single model is not practical. We have updated the readme with results from current github version (in 5 runs), which conforms with the results reported in the paper. Please provide more details if there are problems in reproducing.
